"""
AI Resume Builder — generates Jake's Resume style LaTeX output via Groq.
"""
from __future__ import annotations

import json
import logging
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel

from app.core.config import settings
from app.core.security import get_current_user_id
from app.db.supabase_client import get_supabase
from app.services.groq_limiter import groq_call

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/resume-builder", tags=["resume-builder"])


# ── Models ────────────────────────────────────────────────────────────────────

class ContactInput(BaseModel):
    name: str
    email: str
    phone: str = ""
    location: str = ""
    linkedin: str = ""
    github: str = ""
    portfolio: str = ""

class EducationInput(BaseModel):
    degree: str
    institution: str
    location: str = ""
    start_date: str = ""
    end_date: str = ""
    gpa: str = ""
    relevant_courses: str = ""

class ExperienceInput(BaseModel):
    title: str
    company: str
    location: str = ""
    start_date: str
    end_date: str = "Present"
    raw_bullets: list[str] = []

class ProjectInput(BaseModel):
    name: str
    tech_stack: str
    description: str
    url: str = ""

class GenerateRequest(BaseModel):
    contact: ContactInput
    education: list[EducationInput] = []
    experience: list[ExperienceInput] = []
    projects: list[ProjectInput] = []
    skills_raw: str = ""        # comma-separated or freeform
    activities: str = ""
    awards: str = ""
    target_job: str = ""        # optional JD for tailoring
    use_active_resume: bool = False   # pull from DB instead of form


# ── Helpers ───────────────────────────────────────────────────────────────────

SYSTEM_PROMPT = (
    "You are an expert resume writer who specialises in ATS-optimised, "
    "impact-driven resumes for top tech and finance companies. "
    "Return ONLY valid JSON — no markdown, no extra text."
)


def _escape_latex(s: str) -> str:
    """Escape special LaTeX characters."""
    replacements = [
        ("\\", r"\textbackslash{}"),
        ("&", r"\&"), ("%", r"\%"), ("$", r"\$"),
        ("#", r"\#"), ("_", r"\_"), ("{", r"\{"), ("}", r"\}"),
        ("~", r"\textasciitilde{}"), ("^", r"\textasciicircum{}"),
    ]
    for old, new in replacements:
        s = s.replace(old, new)
    return s


# Static LaTeX preamble — kept as a plain string so #1 / #2 LaTeX params
# don't collide with Python f-string / comment parsing.
_LATEX_PREAMBLE = r"""%-------------------------
% Jake's Resume Template -- generated by JobSync AI
%-------------------------
\documentclass[letterpaper,11pt]{article}

\usepackage{latexsym}
\usepackage[empty]{fullpage}
\usepackage{titlesec}
\usepackage{marvosym}
\usepackage[usenames,dvipsnames]{color}
\usepackage{verbatim}
\usepackage{enumitem}
\usepackage[hidelinks]{hyperref}
\usepackage{fancyhdr}
\usepackage[english]{babel}
\usepackage{tabularx}
\input{glyphtounicode}

\pagestyle{fancy}
\fancyhf{}
\fancyfoot{}
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0pt}

\addtolength{\oddsidemargin}{-0.6in}
\addtolength{\evensidemargin}{-0.6in}
\addtolength{\textwidth}{1.2in}
\addtolength{\topmargin}{-.6in}
\addtolength{\textheight}{1.2in}

\urlstyle{same}
\raggedbottom
\raggedright
\setlength{\tabcolsep}{0in}

\titleformat{\section}{
  \vspace{-4pt}\scshape\raggedright\large
}{}{0em}{}[\color{black}\titlerule \vspace{-5pt}]

\pdfgentounicode=1

\newcommand{\resumeItem}[1]{\item\small{{#1 \vspace{-2pt}}}}

\newcommand{\resumeSubheading}[4]{
  \vspace{-2pt}\item
    \begin{tabular*}{0.97\textwidth}[t]{l@{\extracolsep{\fill}}r}
      \textbf{#1} & #2 \\
      \textit{\small#3} & \textit{\small #4} \\
    \end{tabular*}\vspace{-7pt}
}

\newcommand{\resumeProjectHeading}[2]{
    \item
    \begin{tabular*}{0.97\textwidth}{l@{\extracolsep{\fill}}r}
      \small#1 & #2 \\
    \end{tabular*}\vspace{-7pt}
}

\newcommand{\resumeSubItem}[1]{\resumeItem{#1}\vspace{-4pt}}
\renewcommand\labelitemii{$\vcenter{\hbox{\tiny$\bullet$}}$}
\newcommand{\resumeSubHeadingListStart}{\begin{itemize}[leftmargin=0.15in, label={}]}
\newcommand{\resumeSubHeadingListEnd}{\end{itemize}}
\newcommand{\resumeItemListStart}{\begin{itemize}}
\newcommand{\resumeItemListEnd}{\end{itemize}\vspace{-5pt}}

\begin{document}
"""


def _build_latex(data: dict) -> str:
    """Generate Jake's Resume LaTeX from structured data dict."""
    c = data.get("contact", {})
    name     = _escape_latex(c.get("name", "Your Name"))
    email    = c.get("email", "")
    phone    = _escape_latex(c.get("phone", ""))
    location = _escape_latex(c.get("location", ""))
    linkedin = c.get("linkedin", "").replace("https://", "").replace("http://", "")
    github   = c.get("github", "").replace("https://", "").replace("http://", "")
    portfolio = c.get("portfolio", "")

    # Build contact line
    contact_parts = []
    if phone:     contact_parts.append(phone)
    if email:     contact_parts.append(rf"\href{{mailto:{email}}}{{\underline{{{_escape_latex(email)}}}}}")
    if linkedin:  contact_parts.append(rf"\href{{https://{linkedin}}}{{\underline{{{_escape_latex(linkedin)}}}}}")
    if github:    contact_parts.append(rf"\href{{https://{github}}}{{\underline{{{_escape_latex(github)}}}}}")
    if portfolio: contact_parts.append(rf"\href{{{portfolio}}}{{\underline{{Portfolio}}}}")
    contact_line = " $|$ ".join(contact_parts)

    # Summary
    summary = _escape_latex(data.get("summary", ""))

    # Education
    edu_tex = ""
    for e in data.get("education", []):
        deg  = _escape_latex(e.get("degree", ""))
        inst = _escape_latex(e.get("institution", ""))
        loc  = _escape_latex(e.get("location", ""))
        sd   = _escape_latex(e.get("start_date", ""))
        ed_  = _escape_latex(e.get("end_date", ""))
        gpa  = _escape_latex(str(e.get("gpa", "")))
        date_str = f"{sd} -- {ed_}" if sd else ed_
        # GPA shown as a sub-item using resumeItemListStart so it renders cleanly
        gpa_block = (
            f"\n      \\resumeItemListStart\n"
            f"        \\resumeItem{{GPA: {gpa}}}\n"
            f"      \\resumeItemListEnd"
        ) if gpa else ""
        edu_tex += (
            f"\n    \\resumeSubheading\n"
            f"      {{{inst}}}{{{loc}}}\n"
            f"      {{{deg}}}{{{date_str}}}"
            f"{gpa_block}"
        )

    # Experience
    exp_tex = ""
    for e in data.get("experience", []):
        title   = _escape_latex(e.get("title", ""))
        company = _escape_latex(e.get("company", ""))
        loc     = _escape_latex(e.get("location", ""))
        sd      = _escape_latex(e.get("start_date", ""))
        ed      = _escape_latex(e.get("end_date", "Present"))
        date_str = f"{sd} -- {ed}" if sd else ed
        bullets = e.get("bullets", [])
        bullet_tex = "\n".join(rf"        \resumeItem{{{_escape_latex(b)}}}" for b in bullets)
        exp_tex += rf"""
    \resumeSubheading
      {{{title}}}{{{date_str}}}
      {{{company}}}{{{loc}}}
      \resumeItemListStart
{bullet_tex}
      \resumeItemListEnd"""

    # Projects
    proj_tex = ""
    for p in data.get("projects", []):
        pname  = _escape_latex(p.get("name", ""))
        stack  = _escape_latex(p.get("tech_stack", ""))
        url    = p.get("url", "")
        bullets = p.get("bullets", [])
        bullet_tex = "\n".join(rf"        \resumeItem{{{_escape_latex(b)}}}" for b in bullets)
        proj_heading = (
            rf"\textbf{{\href{{{url}}}{{{pname}}}}} $|$ \emph{{{stack}}}"
            if url else
            rf"\textbf{{{pname}}} $|$ \emph{{{stack}}}"
        )
        proj_tex += rf"""
      \resumeProjectHeading
          {{{proj_heading}}}{{}}
          \resumeItemListStart
{bullet_tex}
          \resumeItemListEnd"""

    # Skills
    skills_tex = ""
    for category, items in data.get("skills", {}).items():
        if items:
            skills_tex += rf"     \textbf{{{_escape_latex(category)}}}{{: {_escape_latex(', '.join(items))}}} \\" + "\n"

    # Activities
    activities = data.get("activities", [])
    act_tex = ""
    for a in activities:
        act_tex += rf"    \resumeItem{{{_escape_latex(a)}}}" + "\n"

    # Awards
    awards = data.get("awards", [])
    award_tex = ""
    for a in awards:
        award_tex += rf"    \resumeItem{{{_escape_latex(a)}}}" + "\n"

    summary_section = rf"""
%-----------SUMMARY-----------
\section{{Summary}}
  \small{{{summary}}}
""" if summary else ""

    activities_section = rf"""
%-----------ACTIVITIES-----------
\section{{Activities}}
  \resumeItemListStart
{act_tex}  \resumeItemListEnd
""" if act_tex else ""

    awards_section = rf"""
%-----------AWARDS \& ACHIEVEMENTS-----------
\section{{Awards \& Achievements}}
  \resumeItemListStart
{award_tex}  \resumeItemListEnd
""" if award_tex else ""

    body = (
        f"%----------HEADING----------\n"
        f"\\begin{{center}}\n"
        f"    \\textbf{{\\Huge \\scshape {name}}} \\\\ \\vspace{{1pt}}\n"
        f"    \\small {contact_line}\n"
        f"\\end{{center}}\n"
        f"{summary_section}"
        f"%-----------EDUCATION-----------\n"
        f"\\section{{Education}}\n"
        f"  \\resumeSubHeadingListStart\n"
        f"{edu_tex}\n"
        f"  \\resumeSubHeadingListEnd\n\n"
        f"%-----------EXPERIENCE-----------\n"
        f"\\section{{Experience}}\n"
        f"  \\resumeSubHeadingListStart\n"
        f"{exp_tex}\n"
        f"  \\resumeSubHeadingListEnd\n\n"
        f"%-----------PROJECTS-----------\n"
        f"\\section{{Projects}}\n"
        f"    \\resumeSubHeadingListStart\n"
        f"{proj_tex}\n"
        f"    \\resumeSubHeadingListEnd\n"
        f"{activities_section}"
        f"{awards_section}"
        f"%-----------TECHNICAL SKILLS-----------\n"
        f"\\section{{Technical Skills}}\n"
        f" \\begin{{itemize}}[leftmargin=0.15in, label={{}}]\n"
        f"    \\small{{\\item{{\n"
        f"{skills_tex}"
        f"    }}}}\n"
        f" \\end{{itemize}}\n\n"
        f"\\end{{document}}\n"
    )
    return _LATEX_PREAMBLE + body


# ── Endpoints ─────────────────────────────────────────────────────────────────

@router.post("/generate")
async def generate_resume(
    body: GenerateRequest,
    user_id: str = Depends(get_current_user_id),
):
    """
    Use Groq to generate a full Jake's Resume from uploaded resume or form data.
    """
    raw_data: dict = {}
    raw_text: str = ""

    if body.use_active_resume:
        try:
            sb = get_supabase()
            result = (
                sb.table("resumes")
                .select("parsed_data, raw_text")
                .eq("user_id", user_id)
                .eq("is_active", True)
                .limit(1)
                .execute()
            )
            if result.data:
                row = result.data[0]
                raw_data = row.get("parsed_data") or {}
                # raw_sections gives us activities/awards even if parser missed them
                raw_sections = raw_data.get("raw_sections", {})
                raw_text = "\n\n".join(
                    f"[{k.upper()}]\n{v}" for k, v in raw_sections.items() if v.strip()
                )
        except Exception as e:
            logger.warning("Could not fetch active resume", error=str(e))

    if body.use_active_resume:
        user_info = {
            "contact":    raw_data.get("contact", {}),
            "education":  raw_data.get("education", []),
            "experience": raw_data.get("experience", []),
            "projects":   raw_data.get("projects", []),
            "skills":     raw_data.get("skills", []),
            "summary":    raw_data.get("summary", ""),
        }
    else:
        user_info = {
            "contact":    body.contact.model_dump(),
            "education":  [e.model_dump() for e in body.education],
            "experience": [e.model_dump() for e in body.experience],
            "projects":   [p.model_dump() for p in body.projects],
            "skills":     body.skills_raw,
            "activities": body.activities,
            "awards":     body.awards,
        }

    jd_context = f"\n\nTARGET JOB DESCRIPTION (tailor keywords to this):\n{body.target_job[:1000]}" if body.target_job else ""

    raw_context = f"\n\nFULL RESUME RAW TEXT (use this to find activities, awards, projects the parser may have missed):\n{raw_text[:3000]}" if raw_text else ""

    prompt = f"""You are an elite resume writer for top tech and finance companies. Transform this data into a FULL, page-filling, ATS-optimised resume.{jd_context}{raw_context}

PARSED DATA:
{json.dumps(user_info, indent=2)}

STRICT RULES:
1. EVERY experience bullet starts with a powerful action verb (Built, Engineered, Designed, Led, Reduced, Increased, Launched, Automated, Scaled, Optimised, Implemented, Architected...)
2. Write 5-6 bullets per experience role — be specific, detailed, and add approximate metrics where reasonable
3. Each bullet should be 80-140 characters — substantial and impactful, NOT vague one-liners
4. Generate 2-3 projects from the experience if no explicit projects exist
5. Each project gets 2-3 strong bullets describing what was built and the impact
6. Write a compelling 3-sentence professional summary covering: who they are, what they build, what they're driven by
7. Extract ALL activities (clubs, competitions, sports) from raw text — include all of them
8. Extract ALL awards/achievements from raw text — include all of them
9. Organise skills into exactly these 5 categories: Languages, Frameworks/Libraries, Databases, Tools, Cloud
10. Keep all facts (company names, dates, institutions, GPA) EXACTLY as provided — never invent facts
11. The output must be RICH and COMPREHENSIVE enough to fill a full A4 page

Return ONLY this JSON structure:
{{
  "contact": {{"name":"","email":"","phone":"","location":"","linkedin":"","github":"","portfolio":""}},
  "summary": "3-sentence professional summary",
  "education": [{{"degree":"","institution":"","location":"","start_date":"","end_date":"","gpa":""}}],
  "experience": [{{"title":"","company":"","location":"","start_date":"","end_date":"","bullets":["5-6 detailed bullets each"]}}],
  "projects": [{{"name":"","tech_stack":"comma,separated,stack","url":"","bullets":["2-3 strong bullets"]}}],
  "skills": {{"Languages":["..."],"Frameworks/Libraries":["..."],"Databases":["..."],"Tools":["..."],"Cloud":["..."]}},
  "activities": ["Full activity description with year range"],
  "awards": ["Full award description with year"]
}}"""

    try:
        raw = await groq_call(
            model=settings.GROQ_MODEL,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user",   "content": prompt},
            ],
            temperature=0.35,
            max_tokens=4000,
            json_mode=True,
            use_cache=False,
        )
        structured = json.loads(raw)
        latex = _build_latex(structured)
        return {"structured": structured, "latex": latex}

    except Exception as e:
        logger.error("Resume generation failed", exc_info=e)
        raise HTTPException(status_code=502, detail="Could not generate resume")
