"""
AI Resume Builder — tiered AI generation.

Free  : 2 generations/month, powered by JobSynk AI Engine (Groq LLaMA).
Pro   : 5 generations/month, powered by Claude Sonnet (Anthropic).

After hitting the free limit users are shown the Pro upsell.
After hitting the Pro limit they wait until the 1st of next month.
"""
from __future__ import annotations

import asyncio
import json
import logging
from datetime import datetime, timezone
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel

from app.core.config import settings
from app.core.security import get_current_user_id
from app.db.supabase_client import get_supabase
from app.services.claude_client import (
    claude_complete,
    get_user_plan,
    get_monthly_usage,
)
from app.services.groq_limiter import groq_call

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/resume-builder", tags=["resume-builder"])

FREE_RESUME_LIMIT = 2   # free tier
PRO_RESUME_LIMIT  = settings.PRO_MONTHLY_RESUMES   # = 5


def _current_month() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m")


# ── Models ────────────────────────────────────────────────────────────────────

class ContactInput(BaseModel):
    name: str
    email: str
    phone: str = ""
    location: str = ""
    linkedin: str = ""
    github: str = ""
    portfolio: str = ""

class EducationInput(BaseModel):
    degree: str
    institution: str
    location: str = ""
    start_date: str = ""
    end_date: str = ""
    gpa: str = ""
    relevant_courses: str = ""

class ExperienceInput(BaseModel):
    title: str
    company: str
    location: str = ""
    start_date: str
    end_date: str = "Present"
    raw_bullets: list[str] = []

class ProjectInput(BaseModel):
    name: str
    tech_stack: str
    description: str
    url: str = ""

class GenerateRequest(BaseModel):
    contact: ContactInput
    education: list[EducationInput] = []
    experience: list[ExperienceInput] = []
    projects: list[ProjectInput] = []
    skills_raw: str = ""
    activities: str = ""
    awards: str = ""
    target_job: str = ""
    use_active_resume: bool = False
    template: str = "jake"  # jake | minimal | modern | two-column | compact


# ── Helpers ───────────────────────────────────────────────────────────────────

SYSTEM_PROMPT = (
    "You are an expert resume writer who specialises in ATS-optimised, "
    "impact-driven resumes for top tech and finance companies. "
    "Return ONLY valid JSON — no markdown, no extra text."
)


def _escape_latex(s: str) -> str:
    replacements = [
        ("\\", r"\textbackslash{}"),
        ("&", r"\&"), ("%", r"\%"), ("$", r"\$"),
        ("#", r"\#"), ("_", r"\_"), ("{", r"\{"), ("}", r"\}"),
        ("~", r"\textasciitilde{}"), ("^", r"\textasciicircum{}"),
    ]
    for old, new in replacements:
        s = s.replace(old, new)
    return s


_LATEX_PREAMBLE = r"""%-------------------------
% Jake's Resume Template -- generated by JobSync AI
%-------------------------
\documentclass[letterpaper,11pt]{article}

\usepackage{latexsym}
\usepackage[empty]{fullpage}
\usepackage{titlesec}
\usepackage{marvosym}
\usepackage[usenames,dvipsnames]{color}
\usepackage{verbatim}
\usepackage{enumitem}
\usepackage[hidelinks]{hyperref}
\usepackage{fancyhdr}
\usepackage[english]{babel}
\usepackage{tabularx}
\input{glyphtounicode}

\pagestyle{fancy}
\fancyhf{}
\fancyfoot{}
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0pt}

\addtolength{\oddsidemargin}{-0.6in}
\addtolength{\evensidemargin}{-0.6in}
\addtolength{\textwidth}{1.2in}
\addtolength{\topmargin}{-.6in}
\addtolength{\textheight}{1.2in}

\urlstyle{same}
\raggedbottom
\raggedright
\setlength{\tabcolsep}{0in}

\titleformat{\section}{
  \vspace{-4pt}\scshape\raggedright\large
}{}{0em}{}[\color{black}\titlerule \vspace{-5pt}]

\pdfgentounicode=1

\newcommand{\resumeItem}[1]{\item\small{{#1 \vspace{-2pt}}}}

\newcommand{\resumeSubheading}[4]{
  \vspace{-2pt}\item
    \begin{tabular*}{0.97\textwidth}[t]{l@{\extracolsep{\fill}}r}
      \textbf{#1} & #2 \\
      \textit{\small#3} & \textit{\small #4} \\
    \end{tabular*}\vspace{-7pt}
}

\newcommand{\resumeProjectHeading}[2]{
    \item
    \begin{tabular*}{0.97\textwidth}{l@{\extracolsep{\fill}}r}
      \small#1 & #2 \\
    \end{tabular*}\vspace{-7pt}
}

\newcommand{\resumeSubItem}[1]{\resumeItem{#1}\vspace{-4pt}}
\renewcommand\labelitemii{$\vcenter{\hbox{\tiny$\bullet$}}$}
\newcommand{\resumeSubHeadingListStart}{\begin{itemize}[leftmargin=0.15in, label={}]}
\newcommand{\resumeSubHeadingListEnd}{\end{itemize}}
\newcommand{\resumeItemListStart}{\begin{itemize}}
\newcommand{\resumeItemListEnd}{\end{itemize}\vspace{-5pt}}

\begin{document}
"""


def _build_latex_jake(data: dict) -> str:
    c = data.get("contact", {})
    name     = _escape_latex(c.get("name", "Your Name"))
    email    = c.get("email", "")
    phone    = _escape_latex(c.get("phone", ""))
    location = _escape_latex(c.get("location", ""))
    linkedin = c.get("linkedin", "").replace("https://", "").replace("http://", "")
    github   = c.get("github", "").replace("https://", "").replace("http://", "")
    portfolio = c.get("portfolio", "")

    contact_parts = []
    if phone:     contact_parts.append(phone)
    if email:     contact_parts.append(rf"\href{{mailto:{email}}}{{\underline{{{_escape_latex(email)}}}}}")
    if linkedin:  contact_parts.append(rf"\href{{https://{linkedin}}}{{\underline{{{_escape_latex(linkedin)}}}}}")
    if github:    contact_parts.append(rf"\href{{https://{github}}}{{\underline{{{_escape_latex(github)}}}}}")
    if portfolio: contact_parts.append(rf"\href{{{portfolio}}}{{\underline{{Portfolio}}}}")
    contact_line = " $|$ ".join(contact_parts)

    summary = _escape_latex(data.get("summary", ""))

    edu_tex = ""
    for e in data.get("education", []):
        deg  = _escape_latex(e.get("degree", ""))
        inst = _escape_latex(e.get("institution", ""))
        loc  = _escape_latex(e.get("location", ""))
        sd   = _escape_latex(e.get("start_date", ""))
        ed_  = _escape_latex(e.get("end_date", ""))
        gpa  = _escape_latex(str(e.get("gpa", "")))
        date_str = f"{sd} -- {ed_}" if sd else ed_
        gpa_block = (
            f"\n      \\resumeItemListStart\n"
            f"        \\resumeItem{{GPA: {gpa}}}\n"
            f"      \\resumeItemListEnd"
        ) if gpa else ""
        edu_tex += (
            f"\n    \\resumeSubheading\n"
            f"      {{{inst}}}{{{loc}}}\n"
            f"      {{{deg}}}{{{date_str}}}"
            f"{gpa_block}"
        )

    exp_tex = ""
    for e in data.get("experience", []):
        title   = _escape_latex(e.get("title", ""))
        company = _escape_latex(e.get("company", ""))
        loc     = _escape_latex(e.get("location", ""))
        sd      = _escape_latex(e.get("start_date", ""))
        ed      = _escape_latex(e.get("end_date", "Present"))
        date_str = f"{sd} -- {ed}" if sd else ed
        bullets = e.get("bullets", [])
        bullet_tex = "\n".join(rf"        \resumeItem{{{_escape_latex(b)}}}" for b in bullets)
        exp_tex += rf"""
    \resumeSubheading
      {{{title}}}{{{date_str}}}
      {{{company}}}{{{loc}}}
      \resumeItemListStart
{bullet_tex}
      \resumeItemListEnd"""

    proj_tex = ""
    for p in data.get("projects", []):
        pname  = _escape_latex(p.get("name", ""))
        stack  = _escape_latex(p.get("tech_stack", ""))
        url    = p.get("url", "")
        bullets = p.get("bullets", [])
        bullet_tex = "\n".join(rf"        \resumeItem{{{_escape_latex(b)}}}" for b in bullets)
        proj_heading = (
            rf"\textbf{{\href{{{url}}}{{{pname}}}}} $|$ \emph{{{stack}}}"
            if url else
            rf"\textbf{{{pname}}} $|$ \emph{{{stack}}}"
        )
        proj_tex += rf"""
      \resumeProjectHeading
          {{{proj_heading}}}{{}}
          \resumeItemListStart
{bullet_tex}
          \resumeItemListEnd"""

    skills_tex = ""
    for category, items in data.get("skills", {}).items():
        if items:
            skills_tex += rf"     \textbf{{{_escape_latex(category)}}}{{: {_escape_latex(', '.join(items))}}} \\" + "\n"

    activities = data.get("activities", [])
    act_tex = ""
    for a in activities:
        act_tex += rf"    \resumeItem{{{_escape_latex(a)}}}" + "\n"

    awards = data.get("awards", [])
    award_tex = ""
    for a in awards:
        award_tex += rf"    \resumeItem{{{_escape_latex(a)}}}" + "\n"

    summary_section = rf"""
%-----------SUMMARY-----------
\section{{Summary}}
  \small{{{summary}}}
""" if summary else ""

    activities_section = rf"""
%-----------ACTIVITIES-----------
\section{{Activities}}
  \resumeItemListStart
{act_tex}  \resumeItemListEnd
""" if act_tex else ""

    awards_section = rf"""
%-----------AWARDS \& ACHIEVEMENTS-----------
\section{{Awards \& Achievements}}
  \resumeItemListStart
{award_tex}  \resumeItemListEnd
""" if award_tex else ""

    body = (
        f"%----------HEADING----------\n"
        f"\\begin{{center}}\n"
        f"    \\textbf{{\\Huge \\scshape {name}}} \\\\ \\vspace{{1pt}}\n"
        f"    \\small {contact_line}\n"
        f"\\end{{center}}\n"
        f"{summary_section}"
        f"%-----------EDUCATION-----------\n"
        f"\\section{{Education}}\n"
        f"  \\resumeSubHeadingListStart\n"
        f"{edu_tex}\n"
        f"  \\resumeSubHeadingListEnd\n\n"
        f"%-----------EXPERIENCE-----------\n"
        f"\\section{{Experience}}\n"
        f"  \\resumeSubHeadingListStart\n"
        f"{exp_tex}\n"
        f"  \\resumeSubHeadingListEnd\n\n"
        f"%-----------PROJECTS-----------\n"
        f"\\section{{Projects}}\n"
        f"    \\resumeSubHeadingListStart\n"
        f"{proj_tex}\n"
        f"    \\resumeSubHeadingListEnd\n"
        f"{activities_section}"
        f"{awards_section}"
        f"%-----------TECHNICAL SKILLS-----------\n"
        f"\\section{{Technical Skills}}\n"
        f" \\begin{{itemize}}[leftmargin=0.15in, label={{}}]\n"
        f"    \\small{{\\item{{\n"
        f"{skills_tex}"
        f"    }}}}\n"
        f" \\end{{itemize}}\n\n"
        f"\\end{{document}}\n"
    )
    return _LATEX_PREAMBLE + body


# ── Template: Minimal ─────────────────────────────────────────────────────────

_LATEX_MINIMAL_PREAMBLE = r"""%-------------------------
% Minimal Resume Template — generated by JobSync AI
%-------------------------
\documentclass[letterpaper,11pt]{article}

\usepackage[top=0.65in,bottom=0.65in,left=0.75in,right=0.75in]{geometry}
\usepackage{enumitem}
\usepackage[hidelinks]{hyperref}
\usepackage[T1]{fontenc}
\usepackage{microtype}
\input{glyphtounicode}
\pdfgentounicode=1

\pagestyle{empty}
\setlength{\parindent}{0pt}
\setlist[itemize]{leftmargin=1.2em,itemsep=1pt,parsep=0pt,topsep=2pt,label=\textbullet}

\newcommand{\msection}[1]{%
  \vspace{6pt}%
  \noindent{\large\bfseries\uppercase{#1}}%
  \vspace{2pt}\hrule\vspace{4pt}%
}

\begin{document}
"""


def _build_latex_minimal(data: dict) -> str:
    c = data.get("contact", {})
    name     = _escape_latex(c.get("name", "Your Name"))
    email    = c.get("email", "")
    phone    = _escape_latex(c.get("phone", ""))
    location = _escape_latex(c.get("location", ""))
    linkedin = c.get("linkedin", "").replace("https://", "").replace("http://", "")
    github   = c.get("github", "").replace("https://", "").replace("http://", "")

    contact_parts = []
    if phone:    contact_parts.append(phone)
    if email:    contact_parts.append(rf"\href{{mailto:{email}}}{{{_escape_latex(email)}}}")
    if location: contact_parts.append(location)
    if linkedin: contact_parts.append(rf"\href{{https://{linkedin}}}{{{_escape_latex(linkedin)}}}")
    if github:   contact_parts.append(rf"\href{{https://{github}}}{{{_escape_latex(github)}}}")
    contact_line = " $\cdot$ ".join(contact_parts)

    summary = _escape_latex(data.get("summary", ""))

    edu_tex = ""
    for e in data.get("education", []):
        deg  = _escape_latex(e.get("degree", ""))
        inst = _escape_latex(e.get("institution", ""))
        loc  = _escape_latex(e.get("location", ""))
        sd   = _escape_latex(e.get("start_date", ""))
        ed_  = _escape_latex(e.get("end_date", ""))
        gpa  = _escape_latex(str(e.get("gpa", "")))
        date_str = f"{sd}--{ed_}" if sd else ed_
        gpa_str = f" \\hfill GPA: {gpa}" if gpa else ""
        edu_tex += (
            f"\\textbf{{{inst}}}, {deg}{gpa_str} \\hfill {_escape_latex(date_str)}\\\\\n"
            f"\\textit{{{loc}}}\\\\\n" if loc else
            f"\\textbf{{{inst}}}, {deg}{gpa_str} \\hfill {_escape_latex(date_str)}\\\\\n"
        )

    exp_tex = ""
    for e in data.get("experience", []):
        title   = _escape_latex(e.get("title", ""))
        company = _escape_latex(e.get("company", ""))
        loc     = _escape_latex(e.get("location", ""))
        sd      = _escape_latex(e.get("start_date", ""))
        ed      = _escape_latex(e.get("end_date", "Present"))
        date_str = f"{sd}--{ed}" if sd else ed
        loc_str  = f", {loc}" if loc else ""
        bullets  = e.get("bullets", [])
        bullet_tex = "\n".join(rf"  \item {_escape_latex(b)}" for b in bullets)
        exp_tex += (
            f"\\textbf{{{title}}} --- \\textit{{{company}{loc_str}}} \\hfill {_escape_latex(date_str)}\\\\\n"
            f"\\begin{{itemize}}\n{bullet_tex}\n\\end{{itemize}}\n\n"
        )

    proj_tex = ""
    for p in data.get("projects", []):
        pname   = _escape_latex(p.get("name", ""))
        stack   = _escape_latex(p.get("tech_stack", ""))
        url     = p.get("url", "")
        bullets = p.get("bullets", [])
        bullet_tex = "\n".join(rf"  \item {_escape_latex(b)}" for b in bullets)
        phead = rf"\href{{{url}}}{{\textbf{{{pname}}}}}" if url else rf"\textbf{{{pname}}}"
        proj_tex += (
            f"{phead} \\hfill \\textit{{{stack}}}\\\\\n"
            f"\\begin{{itemize}}\n{bullet_tex}\n\\end{{itemize}}\n\n"
        )

    skills_tex = ""
    for category, items in data.get("skills", {}).items():
        if items:
            skills_tex += f"\\textbf{{{_escape_latex(category)}}}: {_escape_latex(', '.join(items))}\\\\\n"

    activities = data.get("activities", [])
    act_tex = "\n".join(rf"  \item {_escape_latex(a)}" for a in activities)
    awards = data.get("awards", [])
    award_tex = "\n".join(rf"  \item {_escape_latex(a)}" for a in awards)

    summary_section = f"\\msection{{Summary}}\n{summary}\n\n" if summary else ""
    act_section = f"\\msection{{Activities}}\n\\begin{{itemize}}\n{act_tex}\n\\end{{itemize}}\n" if act_tex else ""
    award_section = f"\\msection{{Awards \\& Achievements}}\n\\begin{{itemize}}\n{award_tex}\n\\end{{itemize}}\n" if award_tex else ""

    body = (
        f"\\noindent{{\\LARGE\\bfseries {name}}}\\\\[3pt]\n"
        f"\\noindent{{\\small {contact_line}}}\\\\[2pt]\n\n"
        f"{summary_section}"
        f"\\msection{{Education}}\n{edu_tex}\n"
        f"\\msection{{Experience}}\n{exp_tex}"
        f"\\msection{{Projects}}\n{proj_tex}"
        f"{act_section}"
        f"{award_section}"
        f"\\msection{{Technical Skills}}\n{skills_tex}\n"
        f"\\end{{document}}\n"
    )
    return _LATEX_MINIMAL_PREAMBLE + body


# ── Template: Modern ──────────────────────────────────────────────────────────

_LATEX_MODERN_PREAMBLE = r"""%-------------------------
% Modern Resume Template — generated by JobSync AI
%-------------------------
\documentclass[letterpaper,11pt]{article}

\usepackage[top=0in,bottom=0.65in,left=0in,right=0in]{geometry}
\usepackage{enumitem}
\usepackage[hidelinks]{hyperref}
\usepackage[T1]{fontenc}
\usepackage{xcolor}
\usepackage{mdframed}
\usepackage{microtype}
\input{glyphtounicode}
\pdfgentounicode=1

\definecolor{headerBg}{RGB}{22,36,56}
\definecolor{accent}{RGB}{78,140,220}

\pagestyle{empty}
\setlength{\parindent}{0pt}
\setlist[itemize]{leftmargin=1.2em,itemsep=1pt,parsep=0pt,topsep=2pt,label={\small\textbullet}}

\newmdenv[
  backgroundcolor=headerBg,
  linewidth=0pt,
  innerleftmargin=28pt,
  innerrightmargin=28pt,
  innertopmargin=16pt,
  innerbottommargin=14pt,
  skipabove=0pt,
  skipbelow=0pt,
]{headerframe}

\newcommand{\msection}[1]{%
  \vspace{7pt}%
  \noindent{\color{accent}\large\bfseries\uppercase{#1}}%
  \vspace{1pt}\\\noindent{\color{accent}\rule{\linewidth}{0.8pt}}\vspace{3pt}%
}

\begin{document}
"""


def _build_latex_modern(data: dict) -> str:
    c = data.get("contact", {})
    name     = _escape_latex(c.get("name", "Your Name"))
    email    = c.get("email", "")
    phone    = _escape_latex(c.get("phone", ""))
    location = _escape_latex(c.get("location", ""))
    linkedin = c.get("linkedin", "").replace("https://", "").replace("http://", "")
    github   = c.get("github", "").replace("https://", "").replace("http://", "")

    contact_parts = []
    if phone:    contact_parts.append(phone)
    if email:    contact_parts.append(rf"\href{{mailto:{email}}}{{{_escape_latex(email)}}}")
    if location: contact_parts.append(location)
    if linkedin: contact_parts.append(rf"\href{{https://{linkedin}}}{{{_escape_latex(linkedin)}}}")
    if github:   contact_parts.append(rf"\href{{https://{github}}}{{{_escape_latex(github)}}}")
    contact_line = " $|$ ".join(contact_parts)

    summary = _escape_latex(data.get("summary", ""))

    edu_tex = ""
    for e in data.get("education", []):
        deg  = _escape_latex(e.get("degree", ""))
        inst = _escape_latex(e.get("institution", ""))
        loc  = _escape_latex(e.get("location", ""))
        sd   = _escape_latex(e.get("start_date", ""))
        ed_  = _escape_latex(e.get("end_date", ""))
        gpa  = _escape_latex(str(e.get("gpa", "")))
        date_str = f"{sd}--{ed_}" if sd else ed_
        gpa_str = f", GPA: {gpa}" if gpa else ""
        edu_tex += (
            f"\\textbf{{{inst}}} \\hfill {_escape_latex(date_str)}\\\\\n"
            f"\\textit{{{deg}{gpa_str}}}{', ' + loc if loc else ''}\\\\\n\n"
        )

    exp_tex = ""
    for e in data.get("experience", []):
        title   = _escape_latex(e.get("title", ""))
        company = _escape_latex(e.get("company", ""))
        loc     = _escape_latex(e.get("location", ""))
        sd      = _escape_latex(e.get("start_date", ""))
        ed      = _escape_latex(e.get("end_date", "Present"))
        date_str = f"{sd}--{ed}" if sd else ed
        loc_str  = f" $\cdot$ {loc}" if loc else ""
        bullets  = e.get("bullets", [])
        bullet_tex = "\n".join(rf"  \item {_escape_latex(b)}" for b in bullets)
        exp_tex += (
            f"\\textbf{{{title}}} \\hfill \\textit{{{_escape_latex(date_str)}}}\\\\\n"
            f"\\textit{{{company}{loc_str}}}\\\\\n"
            f"\\begin{{itemize}}\n{bullet_tex}\n\\end{{itemize}}\n\n"
        )

    proj_tex = ""
    for p in data.get("projects", []):
        pname   = _escape_latex(p.get("name", ""))
        stack   = _escape_latex(p.get("tech_stack", ""))
        url     = p.get("url", "")
        bullets = p.get("bullets", [])
        bullet_tex = "\n".join(rf"  \item {_escape_latex(b)}" for b in bullets)
        phead = rf"\href{{{url}}}{{\textbf{{{pname}}}}}" if url else rf"\textbf{{{pname}}}"
        proj_tex += (
            f"{phead} \\hfill \\textit{{{stack}}}\\\\\n"
            f"\\begin{{itemize}}\n{bullet_tex}\n\\end{{itemize}}\n\n"
        )

    skills_tex = ""
    for category, items in data.get("skills", {}).items():
        if items:
            skills_tex += f"\\textbf{{{_escape_latex(category)}}}: {_escape_latex(', '.join(items))}\\\\\n"

    activities = data.get("activities", [])
    act_tex = "\n".join(rf"  \item {_escape_latex(a)}" for a in activities)
    awards = data.get("awards", [])
    award_tex = "\n".join(rf"  \item {_escape_latex(a)}" for a in awards)

    summary_section = f"\\msection{{Summary}}\n\\noindent {summary}\n" if summary else ""
    act_section = f"\\msection{{Activities}}\n\\begin{{itemize}}\n{act_tex}\n\\end{{itemize}}\n" if act_tex else ""
    award_section = f"\\msection{{Awards \\& Achievements}}\n\\begin{{itemize}}\n{award_tex}\n\\end{{itemize}}\n" if award_tex else ""

    body = (
        f"\\begin{{headerframe}}\n"
        f"  {{\\color{{white}}\\LARGE\\bfseries {name}}}\\\\[4pt]\n"
        f"  {{\\color{{white!70!headerBg}}\\small {contact_line}}}\n"
        f"\\end{{headerframe}}\n\n"
        f"\\begin{{minipage}}[t]{{\\dimexpr\\textwidth-56pt}}\n"
        f"\\hspace{{28pt}}\n"
        f"\\begin{{minipage}}[t]{{\\dimexpr\\textwidth-56pt}}\n\n"
        f"{summary_section}"
        f"\\msection{{Education}}\n{edu_tex}"
        f"\\msection{{Experience}}\n{exp_tex}"
        f"\\msection{{Projects}}\n{proj_tex}"
        f"{act_section}"
        f"{award_section}"
        f"\\msection{{Technical Skills}}\n{skills_tex}\n"
        f"\\end{{minipage}}\n"
        f"\\end{{minipage}}\n\n"
        f"\\end{{document}}\n"
    )
    return _LATEX_MODERN_PREAMBLE + body


# ── Template: Two-Column ──────────────────────────────────────────────────────

_LATEX_TWOCOL_PREAMBLE = r"""%-------------------------
% Two-Column Resume Template — generated by JobSync AI
% Note: Two-column layouts may not parse correctly in all ATS systems.
%-------------------------
\documentclass[letterpaper,10pt]{article}

\usepackage[top=0.5in,bottom=0.5in,left=0.5in,right=0.5in]{geometry}
\usepackage{enumitem}
\usepackage[hidelinks]{hyperref}
\usepackage[T1]{fontenc}
\usepackage{xcolor}
\usepackage{microtype}
\input{glyphtounicode}
\pdfgentounicode=1

\definecolor{sidebarBg}{RGB}{240,243,248}
\definecolor{accent}{RGB}{30,80,160}
\definecolor{lightgray}{RGB}{120,120,120}

\pagestyle{empty}
\setlength{\parindent}{0pt}
\setlist[itemize]{leftmargin=1em,itemsep=0.5pt,parsep=0pt,topsep=2pt,label={\small$\bullet$}}

\newcommand{\shead}[1]{%
  \vspace{6pt}{\color{accent}\small\bfseries\uppercase{#1}}\vspace{2pt}\\%
  {\color{accent!40}\hrule}\vspace{4pt}%
}

\newcommand{\mhead}[1]{%
  \vspace{7pt}{\color{accent}\large\bfseries\uppercase{#1}}\vspace{1pt}\\%
  {\color{accent!50}\rule{\linewidth}{0.6pt}}\vspace{4pt}%
}

\begin{document}
"""


def _build_latex_twocol(data: dict) -> str:
    c = data.get("contact", {})
    name     = _escape_latex(c.get("name", "Your Name"))
    email    = c.get("email", "")
    phone    = _escape_latex(c.get("phone", ""))
    location = _escape_latex(c.get("location", ""))
    linkedin = c.get("linkedin", "").replace("https://", "").replace("http://", "")
    github   = c.get("github", "").replace("https://", "").replace("http://", "")

    summary = _escape_latex(data.get("summary", ""))

    # Left sidebar: contact, skills, education
    left_contact = ""
    if phone:    left_contact += f"{phone}\\\\\n"
    if email:    left_contact += rf"\href{{mailto:{email}}}{{\small {_escape_latex(email)}}}\\" + "\n"
    if location: left_contact += f"{location}\\\\\n"
    if linkedin: left_contact += rf"\href{{https://{linkedin}}}{{\small {_escape_latex(linkedin)}}}\\" + "\n"
    if github:   left_contact += rf"\href{{https://{github}}}{{\small {_escape_latex(github)}}}\\" + "\n"

    skills_tex = ""
    for category, items in data.get("skills", {}).items():
        if items:
            skills_tex += f"\\textbf{{{_escape_latex(category)}}}:\\\\\n"
            skills_tex += f"{{\\small {_escape_latex(', '.join(items))}}}\\\\\n\n"

    edu_tex = ""
    for e in data.get("education", []):
        deg  = _escape_latex(e.get("degree", ""))
        inst = _escape_latex(e.get("institution", ""))
        sd   = _escape_latex(e.get("start_date", ""))
        ed_  = _escape_latex(e.get("end_date", ""))
        gpa  = _escape_latex(str(e.get("gpa", "")))
        date_str = f"{sd}--{ed_}" if sd else ed_
        edu_tex += (
            f"\\textbf{{\\small {inst}}}\\\\\n"
            f"{{\\small {deg}}}\\\\\n"
            f"{{\\small\\color{{lightgray}} {_escape_latex(date_str)}}}"
            + (f"\\\\\n{{\\small GPA: {gpa}}}" if gpa else "") + "\\\\\n\n"
        )

    activities = data.get("activities", [])
    act_tex = "\n".join(rf"  \item {\small " + _escape_latex(a) + "}" for a in activities)
    awards = data.get("awards", [])
    award_tex = "\n".join(rf"  \item {\small " + _escape_latex(a) + "}" for a in awards)

    act_section = f"\\shead{{Activities}}\n\\begin{{itemize}}\n{act_tex}\n\\end{{itemize}}\n" if act_tex else ""
    award_section = f"\\shead{{Awards}}\n\\begin{{itemize}}\n{award_tex}\n\\end{{itemize}}\n" if award_tex else ""

    # Right main: summary, experience, projects
    exp_tex = ""
    for e in data.get("experience", []):
        title   = _escape_latex(e.get("title", ""))
        company = _escape_latex(e.get("company", ""))
        loc     = _escape_latex(e.get("location", ""))
        sd      = _escape_latex(e.get("start_date", ""))
        ed      = _escape_latex(e.get("end_date", "Present"))
        date_str = f"{sd}--{ed}" if sd else ed
        loc_str  = f", {loc}" if loc else ""
        bullets  = e.get("bullets", [])
        bullet_tex = "\n".join(rf"  \item {_escape_latex(b)}" for b in bullets)
        exp_tex += (
            f"\\textbf{{{title}}} \\hfill {{\\small\\color{{lightgray}}{_escape_latex(date_str)}}}\\\\\n"
            f"\\textit{{\\small {company}{loc_str}}}\\\\\n"
            f"\\begin{{itemize}}\n{bullet_tex}\n\\end{{itemize}}\n\n"
        )

    proj_tex = ""
    for p in data.get("projects", []):
        pname   = _escape_latex(p.get("name", ""))
        stack   = _escape_latex(p.get("tech_stack", ""))
        url     = p.get("url", "")
        bullets = p.get("bullets", [])
        bullet_tex = "\n".join(rf"  \item {_escape_latex(b)}" for b in bullets)
        phead = rf"\href{{{url}}}{{\textbf{{{pname}}}}}" if url else rf"\textbf{{{pname}}}"
        proj_tex += (
            f"{phead} $|$ {{\\small\\textit{{{stack}}}}}\\\\\n"
            f"\\begin{{itemize}}\n{bullet_tex}\n\\end{{itemize}}\n\n"
        )

    summary_section = f"\\mhead{{Summary}}\n\\noindent {summary}\n\n" if summary else ""

    body = (
        # Full-width header
        f"\\begin{{center}}\n"
        f"  {{\\Huge\\bfseries {name}}}\\\\[4pt]\n"
        f"\\end{{center}}\n\n"
        f"\\noindent\\rule{{\\linewidth}}{{0.6pt}}\n\n"
        # Two-column layout
        f"\\noindent\n"
        f"\\begin{{minipage}}[t]{{0.30\\textwidth}}\n"
        f"\\vspace{{0pt}}\n"
        f"\\colorbox{{sidebarBg}}{{\\parbox{{\\dimexpr\\linewidth-2\\fboxsep}}{{%\n"
        f"\\vspace{{6pt}}\n"
        f"\\shead{{Contact}}\n{left_contact}\n"
        f"\\shead{{Technical Skills}}\n{skills_tex}\n"
        f"\\shead{{Education}}\n{edu_tex}\n"
        f"{act_section}"
        f"{award_section}"
        f"\\vspace{{6pt}}\n"
        f"}}}}\n"
        f"\\end{{minipage}}%\n"
        f"\\hfill%\n"
        f"\\begin{{minipage}}[t]{{0.66\\textwidth}}\n"
        f"\\vspace{{0pt}}\n"
        f"{summary_section}"
        f"\\mhead{{Experience}}\n{exp_tex}"
        f"\\mhead{{Projects}}\n{proj_tex}"
        f"\\end{{minipage}}\n\n"
        f"\\end{{document}}\n"
    )
    return _LATEX_TWOCOL_PREAMBLE + body


# ── Template: Compact ─────────────────────────────────────────────────────────

_LATEX_COMPACT_PREAMBLE = r"""%-------------------------
% Compact Resume Template — generated by JobSync AI
%-------------------------
\documentclass[letterpaper,10.5pt]{article}

\usepackage{latexsym}
\usepackage[empty]{fullpage}
\usepackage{titlesec}
\usepackage{marvosym}
\usepackage[usenames,dvipsnames]{color}
\usepackage{verbatim}
\usepackage{enumitem}
\usepackage[hidelinks]{hyperref}
\usepackage{fancyhdr}
\usepackage[english]{babel}
\usepackage{tabularx}
\input{glyphtounicode}

\pagestyle{fancy}
\fancyhf{}
\fancyfoot{}
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0pt}

\addtolength{\oddsidemargin}{-0.65in}
\addtolength{\evensidemargin}{-0.65in}
\addtolength{\textwidth}{1.3in}
\addtolength{\topmargin}{-.75in}
\addtolength{\textheight}{1.5in}

\urlstyle{same}
\raggedbottom
\raggedright
\setlength{\tabcolsep}{0in}

\titleformat{\section}{
  \vspace{-6pt}\scshape\raggedright\normalsize
}{}{0em}{}[\color{black}\titlerule \vspace{-5pt}]

\pdfgentounicode=1

\newcommand{\resumeItem}[1]{\item\small{{#1 \vspace{-3pt}}}}

\newcommand{\resumeSubheading}[4]{
  \vspace{-3pt}\item
    \begin{tabular*}{0.97\textwidth}[t]{l@{\extracolsep{\fill}}r}
      \textbf{#1} & \small #2 \\
      \textit{\small#3} & \textit{\small #4} \\
    \end{tabular*}\vspace{-8pt}
}

\newcommand{\resumeProjectHeading}[2]{
    \item
    \begin{tabular*}{0.97\textwidth}{l@{\extracolsep{\fill}}r}
      \small#1 & #2 \\
    \end{tabular*}\vspace{-8pt}
}

\renewcommand\labelitemii{$\vcenter{\hbox{\tiny$\bullet$}}$}
\newcommand{\resumeSubHeadingListStart}{\begin{itemize}[leftmargin=0.15in, label={}]}
\newcommand{\resumeSubHeadingListEnd}{\end{itemize}}
\newcommand{\resumeItemListStart}{\begin{itemize}}
\newcommand{\resumeItemListEnd}{\end{itemize}\vspace{-6pt}}

\begin{document}
"""


def _build_latex_compact(data: dict) -> str:
    """Jake's layout with tighter spacing for fitting more content on one page."""
    c = data.get("contact", {})
    name     = _escape_latex(c.get("name", "Your Name"))
    email    = c.get("email", "")
    phone    = _escape_latex(c.get("phone", ""))
    location = _escape_latex(c.get("location", ""))
    linkedin = c.get("linkedin", "").replace("https://", "").replace("http://", "")
    github   = c.get("github", "").replace("https://", "").replace("http://", "")

    contact_parts = []
    if phone:    contact_parts.append(phone)
    if email:    contact_parts.append(rf"\href{{mailto:{email}}}{{\underline{{{_escape_latex(email)}}}}}")
    if location: contact_parts.append(location)
    if linkedin: contact_parts.append(rf"\href{{https://{linkedin}}}{{\underline{{{_escape_latex(linkedin)}}}}}")
    if github:   contact_parts.append(rf"\href{{https://{github}}}{{\underline{{{_escape_latex(github)}}}}}")
    contact_line = " $|$ ".join(contact_parts)

    summary = _escape_latex(data.get("summary", ""))

    edu_tex = ""
    for e in data.get("education", []):
        deg  = _escape_latex(e.get("degree", ""))
        inst = _escape_latex(e.get("institution", ""))
        loc  = _escape_latex(e.get("location", ""))
        sd   = _escape_latex(e.get("start_date", ""))
        ed_  = _escape_latex(e.get("end_date", ""))
        gpa  = _escape_latex(str(e.get("gpa", "")))
        date_str = f"{sd} -- {ed_}" if sd else ed_
        gpa_block = (
            f"\n      \\resumeItemListStart\n"
            f"        \\resumeItem{{GPA: {gpa}}}\n"
            f"      \\resumeItemListEnd"
        ) if gpa else ""
        edu_tex += (
            f"\n    \\resumeSubheading\n"
            f"      {{{inst}}}{{{loc}}}\n"
            f"      {{{deg}}}{{{date_str}}}"
            f"{gpa_block}"
        )

    exp_tex = ""
    for e in data.get("experience", []):
        title   = _escape_latex(e.get("title", ""))
        company = _escape_latex(e.get("company", ""))
        loc     = _escape_latex(e.get("location", ""))
        sd      = _escape_latex(e.get("start_date", ""))
        ed      = _escape_latex(e.get("end_date", "Present"))
        date_str = f"{sd} -- {ed}" if sd else ed
        bullets = e.get("bullets", [])
        bullet_tex = "\n".join(rf"        \resumeItem{{{_escape_latex(b)}}}" for b in bullets)
        exp_tex += rf"""
    \resumeSubheading
      {{{title}}}{{{date_str}}}
      {{{company}}}{{{loc}}}
      \resumeItemListStart
{bullet_tex}
      \resumeItemListEnd"""

    proj_tex = ""
    for p in data.get("projects", []):
        pname  = _escape_latex(p.get("name", ""))
        stack  = _escape_latex(p.get("tech_stack", ""))
        url    = p.get("url", "")
        bullets = p.get("bullets", [])
        bullet_tex = "\n".join(rf"        \resumeItem{{{_escape_latex(b)}}}" for b in bullets)
        proj_heading = (
            rf"\textbf{{\href{{{url}}}{{{pname}}}}} $|$ \emph{{{stack}}}"
            if url else
            rf"\textbf{{{pname}}} $|$ \emph{{{stack}}}"
        )
        proj_tex += rf"""
      \resumeProjectHeading
          {{{proj_heading}}}{{}}
          \resumeItemListStart
{bullet_tex}
          \resumeItemListEnd"""

    skills_tex = ""
    for category, items in data.get("skills", {}).items():
        if items:
            skills_tex += rf"     \textbf{{{_escape_latex(category)}}}{{: {_escape_latex(', '.join(items))}}} \\" + "\n"

    activities = data.get("activities", [])
    act_tex = "".join(rf"    \resumeItem{{{_escape_latex(a)}}}" + "\n" for a in activities)
    awards = data.get("awards", [])
    award_tex = "".join(rf"    \resumeItem{{{_escape_latex(a)}}}" + "\n" for a in awards)

    summary_section = rf"""
%-----------SUMMARY-----------
\section{{Summary}}
  \small{{{summary}}}
""" if summary else ""

    act_section = rf"""
%-----------ACTIVITIES-----------
\section{{Activities}}
  \resumeItemListStart
{act_tex}  \resumeItemListEnd
""" if act_tex else ""

    award_section = rf"""
%-----------AWARDS-----------
\section{{Awards \& Achievements}}
  \resumeItemListStart
{award_tex}  \resumeItemListEnd
""" if award_tex else ""

    body = (
        f"%----------HEADING----------\n"
        f"\\begin{{center}}\n"
        f"    \\textbf{{\\huge\\scshape {name}}} \\\\ \\vspace{{1pt}}\n"
        f"    \\small {contact_line}\n"
        f"\\end{{center}}\n"
        f"{summary_section}"
        f"%-----------EDUCATION-----------\n"
        f"\\section{{Education}}\n"
        f"  \\resumeSubHeadingListStart\n"
        f"{edu_tex}\n"
        f"  \\resumeSubHeadingListEnd\n\n"
        f"%-----------EXPERIENCE-----------\n"
        f"\\section{{Experience}}\n"
        f"  \\resumeSubHeadingListStart\n"
        f"{exp_tex}\n"
        f"  \\resumeSubHeadingListEnd\n\n"
        f"%-----------PROJECTS-----------\n"
        f"\\section{{Projects}}\n"
        f"    \\resumeSubHeadingListStart\n"
        f"{proj_tex}\n"
        f"    \\resumeSubHeadingListEnd\n"
        f"{act_section}"
        f"{award_section}"
        f"%-----------TECHNICAL SKILLS-----------\n"
        f"\\section{{Technical Skills}}\n"
        f" \\begin{{itemize}}[leftmargin=0.15in, label={{}}]\n"
        f"    \\small{{\\item{{\n"
        f"{skills_tex}"
        f"    }}}}\n"
        f" \\end{{itemize}}\n\n"
        f"\\end{{document}}\n"
    )
    return _LATEX_COMPACT_PREAMBLE + body


# ── Template dispatcher ───────────────────────────────────────────────────────

_TEMPLATE_BUILDERS = {
    "jake":       _build_latex_jake,
    "minimal":    _build_latex_minimal,
    "modern":     _build_latex_modern,
    "two-column": _build_latex_twocol,
    "compact":    _build_latex_compact,
}


def _build_latex(data: dict, template: str = "jake") -> str:
    builder = _TEMPLATE_BUILDERS.get(template, _build_latex_jake)
    return builder(data)


async def _increment_resume_count(user_id: str) -> None:
    """Atomically increment resume_count in monthly_usage (fire-and-forget)."""
    supabase = get_supabase()
    month = _current_month()
    try:
        await asyncio.to_thread(
            lambda: supabase.rpc("increment_monthly_usage", {
                "p_user_id":     user_id,
                "p_month":       month,
                "p_feature_col": "resume_count",
                "p_tokens":      0,
                "p_cost_inr":    0,
                "p_chat_tokens": 0,
            }).execute()
        )
    except Exception as e:
        logger.warning("Failed to increment resume count: %s", e)


# ── Endpoints ─────────────────────────────────────────────────────────────────

@router.get("/status")
async def resume_builder_status(user_id: str = Depends(get_current_user_id)):
    """
    Returns the user's current resume generation quota.
    Used by the frontend to show the usage meter + correct AI label.
    """
    plan  = await get_user_plan(user_id)
    usage = await get_monthly_usage(user_id)
    used  = usage.get("resume_count", 0)

    if plan == "pro":
        limit = PRO_RESUME_LIMIT
        model = "claude-sonnet"
    else:
        limit = FREE_RESUME_LIMIT
        model = "jobsynk-ai"

    return {
        "plan":            plan,
        "model":           model,
        "uses_used":       used,
        "uses_limit":      limit,
        "uses_remaining":  max(0, limit - used),
        "locked":          used >= limit,
        "requires_pro":    plan == "free" and used >= FREE_RESUME_LIMIT,
    }


@router.post("/generate")
async def generate_resume(
    body: GenerateRequest,
    user_id: str = Depends(get_current_user_id),
):
    """
    Tiered resume generation:
      Free       → JobSynk AI Engine (Groq LLaMA-3.3-70b), limit 2/month
      Credit     → Claude Sonnet, 1 credit per generation (resume_pack purchase)
      Pro        → Claude Sonnet, limit 5/month
    """
    plan  = await get_user_plan(user_id)
    usage = await get_monthly_usage(user_id)
    used  = usage.get("resume_count", 0)

    # ── Check for purchased resume_pack credits (non-Pro) ────────────────────
    using_credit = False
    if plan != "pro":
        sb = get_supabase()
        credit = await asyncio.to_thread(
            lambda: sb.table("user_credits")
            .select("id, credits_remaining")
            .eq("user_id", user_id)
            .eq("credit_type", "resume_pack")
            .gt("credits_remaining", 0)
            .order("created_at")
            .limit(1)
            .execute()
        )
        if credit.data:
            # Consume 1 credit and unlock Claude for this generation
            row = credit.data[0]
            await asyncio.to_thread(
                lambda: sb.table("user_credits")
                .update({"credits_remaining": row["credits_remaining"] - 1})
                .eq("id", row["id"])
                .execute()
            )
            using_credit = True
            plan = "pro"  # treat as Pro for this request
            logger.info("Resume pack credit consumed for user %s (remaining: %d)", user_id, row["credits_remaining"] - 1)

    if plan == "pro":
        if not using_credit and used >= PRO_RESUME_LIMIT:
            raise HTTPException(
                status_code=429,
                detail=f"Monthly limit reached ({PRO_RESUME_LIMIT} resumes/month on Pro). Resets on the 1st.",
            )
    else:
        if used >= FREE_RESUME_LIMIT:
            raise HTTPException(
                status_code=402,
                detail=f"Free limit reached ({FREE_RESUME_LIMIT} resumes/month). Upgrade to Pro for {PRO_RESUME_LIMIT}/month with Claude Sonnet.",
            )

    # ── Build user data dict ─────────────────────────────────────────────────
    raw_data: dict = {}
    raw_text: str = ""

    if body.use_active_resume:
        try:
            sb = get_supabase()
            result = await asyncio.to_thread(
                lambda: sb.table("resumes")
                .select("parsed_data, raw_text")
                .eq("user_id", user_id)
                .eq("is_active", True)
                .limit(1)
                .execute()
            )
            if result.data:
                row = result.data[0]
                raw_data = row.get("parsed_data") or {}
                raw_sections = raw_data.get("raw_sections", {})
                raw_text = "\n\n".join(
                    f"[{k.upper()}]\n{v}" for k, v in raw_sections.items() if v.strip()
                )
        except Exception as e:
            logger.warning("Could not fetch active resume: %s", e)

    if body.use_active_resume:
        user_info = {
            "contact":    raw_data.get("contact", {}),
            "education":  raw_data.get("education", []),
            "experience": raw_data.get("experience", []),
            "projects":   raw_data.get("projects", []),
            "skills":     raw_data.get("skills", []),
            "summary":    raw_data.get("summary", ""),
        }
    else:
        user_info = {
            "contact":    body.contact.model_dump(),
            "education":  [e.model_dump() for e in body.education],
            "experience": [e.model_dump() for e in body.experience],
            "projects":   [p.model_dump() for p in body.projects],
            "skills":     body.skills_raw,
            "activities": body.activities,
            "awards":     body.awards,
        }

    jd_context  = f"\n\nTARGET JOB DESCRIPTION (tailor keywords to this):\n{body.target_job[:1000]}" if body.target_job else ""
    raw_context = f"\n\nFULL RESUME RAW TEXT (use this to find activities, awards, projects the parser may have missed):\n{raw_text[:3000]}" if raw_text else ""

    prompt = f"""You are an elite resume writer for top tech and finance companies. Transform this data into a FULL, page-filling, ATS-optimised resume.{jd_context}{raw_context}

PARSED DATA:
{json.dumps(user_info, indent=2)}

STRICT RULES:
1. EVERY experience bullet starts with a powerful action verb (Built, Engineered, Designed, Led, Reduced, Increased, Launched, Automated, Scaled, Optimised, Implemented, Architected...)
2. Write 5-6 bullets per experience role — be specific, detailed, and add approximate metrics where reasonable
3. Each bullet should be 80-140 characters — substantial and impactful, NOT vague one-liners
4. Generate 2-3 projects from the experience if no explicit projects exist
5. Each project gets 2-3 strong bullets describing what was built and the impact
6. Write a compelling 3-sentence professional summary covering: who they are, what they build, what they're driven by
7. Extract ALL activities (clubs, competitions, sports) from raw text — include all of them
8. Extract ALL awards/achievements from raw text — include all of them
9. Organise skills into exactly these 5 categories: Languages, Frameworks/Libraries, Databases, Tools, Cloud
10. Keep all facts (company names, dates, institutions, GPA) EXACTLY as provided — never invent facts
11. The output must be RICH and COMPREHENSIVE enough to fill a full A4 page

Return ONLY this JSON structure:
{{
  "contact": {{"name":"","email":"","phone":"","location":"","linkedin":"","github":"","portfolio":""}},
  "summary": "3-sentence professional summary",
  "education": [{{"degree":"","institution":"","location":"","start_date":"","end_date":"","gpa":""}}],
  "experience": [{{"title":"","company":"","location":"","start_date":"","end_date":"","bullets":["5-6 detailed bullets each"]}}],
  "projects": [{{"name":"","tech_stack":"comma,separated,stack","url":"","bullets":["2-3 strong bullets"]}}],
  "skills": {{"Languages":["..."],"Frameworks/Libraries":["..."],"Databases":["..."],"Tools":["..."],"Cloud":["..."]}},
  "activities": ["Full activity description with year range"],
  "awards": ["Full award description with year"]
}}"""

    try:
        if plan == "pro":
            # ── Pro: Claude Sonnet ───────────────────────────────────────────
            raw = await claude_complete(
                user_id=user_id,
                feature="resume",
                system=SYSTEM_PROMPT,
                messages=[{"role": "user", "content": prompt}],
                max_tokens=4000,
                skip_quota_check=True,   # already checked above
            )
            model_used = "claude-sonnet"
        else:
            # ── Free: JobSynk AI Engine (Groq) ───────────────────────────────
            raw = await groq_call(
                model=settings.GROQ_MODEL,
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user",   "content": prompt},
                ],
                temperature=0.35,
                max_tokens=4000,
                json_mode=True,
                use_cache=False,
            )
            model_used = "jobsynk-ai"
            # Increment free usage counter (fire-and-forget)
            asyncio.create_task(_increment_resume_count(user_id))

        structured = json.loads(raw)
        latex = _build_latex(structured, template=body.template)

        # Calculate remaining after this generation
        new_used = used + 1
        limit = PRO_RESUME_LIMIT if plan == "pro" else FREE_RESUME_LIMIT

        return {
            "structured":      structured,
            "latex":           latex,
            "model_used":      model_used,
            "template":        body.template,
            "uses_used":       new_used,
            "uses_remaining":  max(0, limit - new_used),
            "uses_limit":      limit,
        }

    except HTTPException:
        raise
    except Exception as e:
        logger.error("Resume generation failed", exc_info=e)
        raise HTTPException(status_code=502, detail="Could not generate resume. Please try again.")
