"""
AI Resume Builder — generates Jake's Resume style LaTeX output via Groq.
"""
from __future__ import annotations

import json
import logging
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel

from app.core.config import settings
from app.core.security import get_current_user_id
from app.db.supabase_client import get_supabase
from app.services.groq_limiter import groq_call

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/resume-builder", tags=["resume-builder"])


# ── Models ────────────────────────────────────────────────────────────────────

class ContactInput(BaseModel):
    name: str
    email: str
    phone: str = ""
    location: str = ""
    linkedin: str = ""
    github: str = ""
    portfolio: str = ""

class EducationInput(BaseModel):
    degree: str
    institution: str
    location: str = ""
    start_date: str = ""
    end_date: str = ""
    gpa: str = ""
    relevant_courses: str = ""

class ExperienceInput(BaseModel):
    title: str
    company: str
    location: str = ""
    start_date: str
    end_date: str = "Present"
    raw_bullets: list[str] = []

class ProjectInput(BaseModel):
    name: str
    tech_stack: str
    description: str
    url: str = ""

class GenerateRequest(BaseModel):
    contact: ContactInput
    education: list[EducationInput] = []
    experience: list[ExperienceInput] = []
    projects: list[ProjectInput] = []
    skills_raw: str = ""        # comma-separated or freeform
    activities: str = ""
    awards: str = ""
    target_job: str = ""        # optional JD for tailoring
    use_active_resume: bool = False   # pull from DB instead of form


# ── Helpers ───────────────────────────────────────────────────────────────────

SYSTEM_PROMPT = (
    "You are an expert resume writer who specialises in ATS-optimised, "
    "impact-driven resumes for top tech and finance companies. "
    "Return ONLY valid JSON — no markdown, no extra text."
)


def _escape_latex(s: str) -> str:
    """Escape special LaTeX characters."""
    replacements = [
        ("\\", r"\textbackslash{}"),
        ("&", r"\&"), ("%", r"\%"), ("$", r"\$"),
        ("#", r"\#"), ("_", r"\_"), ("{", r"\{"), ("}", r"\}"),
        ("~", r"\textasciitilde{}"), ("^", r"\textasciicircum{}"),
    ]
    for old, new in replacements:
        s = s.replace(old, new)
    return s


# Static LaTeX preamble — kept as a plain string so #1 / #2 LaTeX params
# don't collide with Python f-string / comment parsing.
_LATEX_PREAMBLE = r"""%-------------------------
% Jake's Resume Template -- generated by JobSync AI
%-------------------------
\documentclass[letterpaper,11pt]{article}

\usepackage{latexsym}
\usepackage[empty]{fullpage}
\usepackage{titlesec}
\usepackage{marvosym}
\usepackage[usenames,dvipsnames]{color}
\usepackage{verbatim}
\usepackage{enumitem}
\usepackage[hidelinks]{hyperref}
\usepackage{fancyhdr}
\usepackage[english]{babel}
\usepackage{tabularx}
\input{glyphtounicode}

\pagestyle{fancy}
\fancyhf{}
\fancyfoot{}
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0pt}

\addtolength{\oddsidemargin}{-0.5in}
\addtolength{\evensidemargin}{-0.5in}
\addtolength{\textwidth}{1in}
\addtolength{\topmargin}{-.5in}
\addtolength{\textheight}{1.0in}

\urlstyle{same}
\raggedbottom
\raggedright
\setlength{\tabcolsep}{0in}

\titleformat{\section}{
  \vspace{-4pt}\scshape\raggedright\large
}{}{0em}{}[\color{black}\titlerule \vspace{-5pt}]

\pdfgentounicode=1

\newcommand{\resumeItem}[1]{\item\small{{#1 \vspace{-2pt}}}}

\newcommand{\resumeSubheading}[4]{
  \vspace{-2pt}\item
    \begin{tabular*}{0.97\textwidth}[t]{l@{\extracolsep{\fill}}r}
      \textbf{#1} & #2 \\
      \textit{\small#3} & \textit{\small #4} \\
    \end{tabular*}\vspace{-7pt}
}

\newcommand{\resumeProjectHeading}[2]{
    \item
    \begin{tabular*}{0.97\textwidth}{l@{\extracolsep{\fill}}r}
      \small#1 & #2 \\
    \end{tabular*}\vspace{-7pt}
}

\newcommand{\resumeSubItem}[1]{\resumeItem{#1}\vspace{-4pt}}
\renewcommand\labelitemii{$\vcenter{\hbox{\tiny$\bullet$}}$}
\newcommand{\resumeSubHeadingListStart}{\begin{itemize}[leftmargin=0.15in, label={}]}
\newcommand{\resumeSubHeadingListEnd}{\end{itemize}}
\newcommand{\resumeItemListStart}{\begin{itemize}}
\newcommand{\resumeItemListEnd}{\end{itemize}\vspace{-5pt}}

\begin{document}
"""


def _build_latex(data: dict) -> str:
    """Generate Jake's Resume LaTeX from structured data dict."""
    c = data.get("contact", {})
    name     = _escape_latex(c.get("name", "Your Name"))
    email    = c.get("email", "")
    phone    = _escape_latex(c.get("phone", ""))
    location = _escape_latex(c.get("location", ""))
    linkedin = c.get("linkedin", "").replace("https://", "").replace("http://", "")
    github   = c.get("github", "").replace("https://", "").replace("http://", "")
    portfolio = c.get("portfolio", "")

    # Build contact line
    contact_parts = []
    if phone:     contact_parts.append(phone)
    if email:     contact_parts.append(rf"\href{{mailto:{email}}}{{\underline{{{_escape_latex(email)}}}}}")
    if linkedin:  contact_parts.append(rf"\href{{https://{linkedin}}}{{\underline{{{_escape_latex(linkedin)}}}}}")
    if github:    contact_parts.append(rf"\href{{https://{github}}}{{\underline{{{_escape_latex(github)}}}}}")
    if portfolio: contact_parts.append(rf"\href{{{portfolio}}}{{\underline{{Portfolio}}}}")
    contact_line = " $|$ ".join(contact_parts)

    # Summary
    summary = _escape_latex(data.get("summary", ""))

    # Education
    edu_tex = ""
    for e in data.get("education", []):
        deg  = _escape_latex(e.get("degree", ""))
        inst = _escape_latex(e.get("institution", ""))
        loc  = _escape_latex(e.get("location", ""))
        sd   = _escape_latex(e.get("start_date", ""))
        ed   = _escape_latex(e.get("end_date", ""))
        gpa  = e.get("gpa", "")
        date_str = f"{sd} -- {ed}" if sd else ed
        gpa_line = rf"        \small{{GPA: {_escape_latex(gpa)}}}" if gpa else ""
        edu_tex += rf"""
    \resumeSubheading
      {{{inst}}}{{{loc}}}
      {{{deg}}}{{{date_str}}}
{gpa_line}"""

    # Experience
    exp_tex = ""
    for e in data.get("experience", []):
        title   = _escape_latex(e.get("title", ""))
        company = _escape_latex(e.get("company", ""))
        loc     = _escape_latex(e.get("location", ""))
        sd      = _escape_latex(e.get("start_date", ""))
        ed      = _escape_latex(e.get("end_date", "Present"))
        date_str = f"{sd} -- {ed}" if sd else ed
        bullets = e.get("bullets", [])
        bullet_tex = "\n".join(rf"        \resumeItem{{{_escape_latex(b)}}}" for b in bullets)
        exp_tex += rf"""
    \resumeSubheading
      {{{title}}}{{{date_str}}}
      {{{company}}}{{{loc}}}
      \resumeItemListStart
{bullet_tex}
      \resumeItemListEnd"""

    # Projects
    proj_tex = ""
    for p in data.get("projects", []):
        pname  = _escape_latex(p.get("name", ""))
        stack  = _escape_latex(p.get("tech_stack", ""))
        url    = p.get("url", "")
        bullets = p.get("bullets", [])
        bullet_tex = "\n".join(rf"        \resumeItem{{{_escape_latex(b)}}}" for b in bullets)
        proj_heading = (
            rf"\textbf{{\href{{{url}}}{{{pname}}}}} $|$ \emph{{{stack}}}"
            if url else
            rf"\textbf{{{pname}}} $|$ \emph{{{stack}}}"
        )
        proj_tex += rf"""
      \resumeProjectHeading
          {{{proj_heading}}}{{}}
          \resumeItemListStart
{bullet_tex}
          \resumeItemListEnd"""

    # Skills
    skills_tex = ""
    for category, items in data.get("skills", {}).items():
        if items:
            skills_tex += rf"     \textbf{{{_escape_latex(category)}}}{{: {_escape_latex(', '.join(items))}}} \\" + "\n"

    # Activities
    activities = data.get("activities", [])
    act_tex = ""
    for a in activities:
        act_tex += rf"    \resumeItem{{{_escape_latex(a)}}}" + "\n"

    # Awards
    awards = data.get("awards", [])
    award_tex = ""
    for a in awards:
        award_tex += rf"    \resumeItem{{{_escape_latex(a)}}}" + "\n"

    summary_section = rf"""
%-----------SUMMARY-----------
\section{{Summary}}
  \small{{{summary}}}
""" if summary else ""

    activities_section = rf"""
%-----------ACTIVITIES-----------
\section{{Activities}}
  \resumeItemListStart
{act_tex}  \resumeItemListEnd
""" if act_tex else ""

    awards_section = rf"""
%-----------AWARDS \& ACHIEVEMENTS-----------
\section{{Awards \& Achievements}}
  \resumeItemListStart
{award_tex}  \resumeItemListEnd
""" if award_tex else ""

    body = (
        f"%----------HEADING----------\n"
        f"\\begin{{center}}\n"
        f"    \\textbf{{\\Huge \\scshape {name}}} \\\\ \\vspace{{1pt}}\n"
        f"    \\small {contact_line}\n"
        f"\\end{{center}}\n"
        f"{summary_section}"
        f"%-----------EDUCATION-----------\n"
        f"\\section{{Education}}\n"
        f"  \\resumeSubHeadingListStart\n"
        f"{edu_tex}\n"
        f"  \\resumeSubHeadingListEnd\n\n"
        f"%-----------EXPERIENCE-----------\n"
        f"\\section{{Experience}}\n"
        f"  \\resumeSubHeadingListStart\n"
        f"{exp_tex}\n"
        f"  \\resumeSubHeadingListEnd\n\n"
        f"%-----------PROJECTS-----------\n"
        f"\\section{{Projects}}\n"
        f"    \\resumeSubHeadingListStart\n"
        f"{proj_tex}\n"
        f"    \\resumeSubHeadingListEnd\n"
        f"{activities_section}"
        f"{awards_section}"
        f"%-----------TECHNICAL SKILLS-----------\n"
        f"\\section{{Technical Skills}}\n"
        f" \\begin{{itemize}}[leftmargin=0.15in, label={{}}]\n"
        f"    \\small{{\\item{{\n"
        f"{skills_tex}"
        f"    }}}}\n"
        f" \\end{{itemize}}\n\n"
        f"\\end{{document}}\n"
    )
    return _LATEX_PREAMBLE + body


# ── Endpoints ─────────────────────────────────────────────────────────────────

@router.post("/generate")
async def generate_resume(
    body: GenerateRequest,
    user_id: str = Depends(get_current_user_id),
):
    """
    Use Groq to turn raw user input (or active resume) into a polished,
    ATS-optimised resume structure, then convert to Jake's Resume LaTeX.
    """
    # Pull from active resume if requested
    raw_data = {}
    if body.use_active_resume:
        try:
            sb = get_supabase()
            result = (
                sb.table("resumes")
                .select("parsed_data")
                .eq("user_id", user_id)
                .eq("is_active", True)
                .limit(1)
                .execute()
            )
            if result.data:
                raw_data = result.data[0].get("parsed_data") or {}
        except Exception as e:
            logger.warning("Could not fetch active resume", error=str(e))

    # Build prompt
    user_info = {
        "contact": body.contact.model_dump() if not body.use_active_resume else raw_data.get("contact", {}),
        "education": [e.model_dump() for e in body.education] if not body.use_active_resume else raw_data.get("education", []),
        "experience": [e.model_dump() for e in body.experience] if not body.use_active_resume else raw_data.get("experience", []),
        "projects":   [p.model_dump() for p in body.projects]   if not body.use_active_resume else raw_data.get("projects", []),
        "skills_raw": body.skills_raw if not body.use_active_resume else ", ".join(raw_data.get("skills", [])),
        "activities": body.activities,
        "awards":     body.awards,
    }

    jd_context = f"\n\nTarget job description:\n{body.target_job[:800]}" if body.target_job else ""

    prompt = f"""You are a professional resume writer. Polish and enhance this resume data into an ATS-optimised, impact-driven resume.{jd_context}

Raw data:
{json.dumps(user_info, indent=2)}

Rules:
- Every experience bullet MUST start with a strong action verb (Built, Led, Designed, Reduced, Increased, etc.)
- Add metrics/numbers wherever you can infer them (even approximate)
- Keep bullets concise (under 120 chars each), max 5 per role
- Write a 2-3 sentence professional summary
- Organise skills into: Languages, Frameworks/Libraries, Databases, Tools, Cloud
- Keep all factual details (company names, dates, institutions) exactly as given
- If target JD provided, weave in relevant keywords naturally

Return JSON with this exact structure:
{{
  "contact": {{"name":"","email":"","phone":"","location":"","linkedin":"","github":"","portfolio":""}},
  "summary": "2-3 sentence summary",
  "education": [{{"degree":"","institution":"","location":"","start_date":"","end_date":"","gpa":""}}],
  "experience": [{{"title":"","company":"","location":"","start_date":"","end_date":"","bullets":["..."]}}],
  "projects": [{{"name":"","tech_stack":"","url":"","bullets":["..."]}}],
  "skills": {{"Languages":[],"Frameworks/Libraries":[],"Databases":[],"Tools":[],"Cloud":[]}},
  "activities": ["..."],
  "awards": ["..."]
}}"""

    try:
        raw = await groq_call(
            model=settings.GROQ_MODEL,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user",   "content": prompt},
            ],
            temperature=0.4,
            max_tokens=3000,
            json_mode=True,
            use_cache=False,
        )
        structured = json.loads(raw)
        latex = _build_latex(structured)
        return {"structured": structured, "latex": latex}

    except Exception as e:
        logger.error("Resume generation failed", exc_info=e)
        raise HTTPException(status_code=502, detail="Could not generate resume")
