"""
Neural Trainer — trains the JobSyncScorer model on synthetic + real data.

Data sources (in priority order):
  1. backend/data/training_pairs.jsonl   — synthetic labeled pairs (generated by Groq)
  2. scoring_feedback table              — real user outcomes (grows over time)

Training strategy:
  - Multi-task MSE loss across all 5 dimensions simultaneously
  - Ranking loss: high-score pairs must rank above low-score pairs
  - Early stopping on validation MSE
  - Saves best checkpoint; metadata updated atomically

Usage:
  python -m app.services.neural_trainer            # train on all available data
  python -m app.services.neural_trainer --epochs 50
  python -m app.services.neural_trainer --fine-tune  # fine-tune existing model on feedback

API trigger:
  POST /api/v1/model/train/neural-scorer
"""
from __future__ import annotations

import argparse
import asyncio
import json
import time
from datetime import datetime
from pathlib import Path
from typing import Optional
import structlog

logger = structlog.get_logger()

DATA_PATH = Path(__file__).resolve().parent.parent.parent / "data" / "training_pairs.jsonl"
MODELS_DIR = Path(__file__).resolve().parent.parent.parent / "models"
MODELS_DIR.mkdir(exist_ok=True)

MIN_SAMPLES = 50      # minimum to start training (synthetic data provides 600+)
BATCH_SIZE = 32
DEFAULT_EPOCHS = 100
LR = 2e-4
WEIGHT_DECAY = 1e-4
PATIENCE = 15         # early stopping patience


# ─── Dataset ───────────────────────────────────────────────────────────────────

class ScoringDataset:
    """
    Loads training pairs from JSONL file.

    Each line must have:
      {
        "resume": str,
        "jd": str,
        "ats_score": float,
        "technical_fit_score": float,
        "semantic_match_score": float,
        "recruiter_impression_score": float,
        "project_relevance_score": float,
      }
    """

    def __init__(self, records: list[dict], embedder):
        import torch
        from app.services.jobsync_neural_scorer import (
            build_interaction_tensor,
            build_handcrafted_features,
            DIMENSION_NAMES,
        )

        self.X = []
        self.y = []
        skipped = 0

        for rec in records:
            try:
                r_emb = embedder.encode(rec["resume"], show_progress_bar=False).tolist()
                j_emb = embedder.encode(rec["jd"], show_progress_bar=False).tolist()
                hc = build_handcrafted_features(rec["resume"], rec["jd"], r_emb, j_emb)
                x = build_interaction_tensor(r_emb, j_emb, hc)

                targets = [float(rec.get(d, 50.0)) for d in DIMENSION_NAMES]
                y = torch.tensor(targets, dtype=torch.float32)

                self.X.append(x.squeeze(0))
                self.y.append(y)
            except Exception as e:
                skipped += 1
                continue

        if skipped:
            logger.warning("Skipped records during embedding", count=skipped)

        logger.info("Dataset built", samples=len(self.X))

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]


# ─── Loss functions ─────────────────────────────────────────────────────────────

def ranking_loss(preds, targets, margin: float = 5.0):
    """
    Pairwise ranking loss.
    If target[i] > target[j] + margin, then pred[i] should > pred[j].
    Uses overall score (mean of all dimensions).
    """
    import torch

    overall_pred = preds.mean(dim=1)    # (batch,)
    overall_tgt = targets.mean(dim=1)   # (batch,)

    n = overall_pred.shape[0]
    loss = torch.tensor(0.0)

    if n < 2:
        return loss

    for i in range(n):
        for j in range(i + 1, n):
            if overall_tgt[i] > overall_tgt[j] + margin:
                # i should score higher than j
                loss = loss + torch.clamp(overall_pred[j] - overall_pred[i] + 1.0, min=0.0)
            elif overall_tgt[j] > overall_tgt[i] + margin:
                loss = loss + torch.clamp(overall_pred[i] - overall_pred[j] + 1.0, min=0.0)

    return loss / (n * (n - 1) / 2 + 1e-8)


def combined_loss(preds, targets, rank_weight: float = 0.2):
    """MSE (regression accuracy) + ranking (relative ordering)."""
    import torch.nn.functional as F
    mse = F.mse_loss(preds, targets)
    rank = ranking_loss(preds, targets)
    return mse + rank_weight * rank, mse, rank


# ─── Training loop ─────────────────────────────────────────────────────────────

def _load_jsonl_data() -> list[dict]:
    """Load synthetic training pairs from JSONL."""
    if not DATA_PATH.exists():
        logger.warning("training_pairs.jsonl not found", path=str(DATA_PATH))
        return []
    records = []
    with DATA_PATH.open() as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
                # Only include records with per-dimension scores
                if all(k in rec for k in ["resume", "jd", "ats_score"]):
                    records.append(rec)
            except json.JSONDecodeError:
                continue
    logger.info("Loaded JSONL training data", records=len(records))
    return records


async def _load_feedback_data() -> list[dict]:
    """Load real user feedback from Supabase as additional training signal."""
    try:
        from app.db.database import get_db_connection
        async with get_db_connection() as conn:
            rows = await conn.fetch(
                """
                SELECT
                    sf.outcome,
                    sf.dimension_scores,
                    sf.accuracy_rating,
                    a.resume_text,
                    a.job_description
                FROM scoring_feedback sf
                JOIN analyses a ON a.id = sf.analysis_id
                WHERE
                    sf.dimension_scores IS NOT NULL
                    AND a.resume_text IS NOT NULL
                    AND a.job_description IS NOT NULL
                LIMIT 5000
                """
            )
    except Exception as e:
        logger.warning("Could not load feedback data", error=str(e))
        return []

    records = []
    OUTCOME_MULTIPLIER = {
        "offer": 1.10,
        "got_interview": 1.05,
        "screening_call": 1.02,
        "no_response": 0.95,
        "rejected": 0.85,
        "withdrew": 1.0,
    }

    for row in rows:
        try:
            ds = row["dimension_scores"]
            if isinstance(ds, str):
                ds = json.loads(ds)

            mult = OUTCOME_MULTIPLIER.get(row["outcome"], 1.0)
            record = {
                "resume": row["resume_text"],
                "jd": row["job_description"],
                "ats_score": min(100.0, float(ds.get("ats_score", 50)) * mult),
                "technical_fit_score": min(100.0, float(ds.get("technical_fit_score", 50)) * mult),
                "semantic_match_score": min(100.0, float(ds.get("semantic_match_score", 50)) * mult),
                "recruiter_impression_score": min(100.0, float(ds.get("recruiter_impression_score", 50)) * mult),
                "project_relevance_score": min(100.0, float(ds.get("project_relevance_score", 50)) * mult),
            }
            records.append(record)
        except Exception:
            continue

    logger.info("Loaded feedback training data", records=len(records))
    return records


def train(
    epochs: int = DEFAULT_EPOCHS,
    fine_tune: bool = False,
    feedback_records: Optional[list[dict]] = None,
) -> dict:
    """
    Train the JobSyncScorer model.

    Args:
        epochs:           Number of training epochs.
        fine_tune:        If True, load existing model and continue training (for feedback updates).
        feedback_records: Optional real feedback records (from async caller).

    Returns:
        Training result dict.
    """
    import torch
    import torch.nn as nn
    import numpy as np
    from torch.utils.data import DataLoader, random_split
    from torch.optim import AdamW
    from torch.optim.lr_scheduler import CosineAnnealingLR
    from sentence_transformers import SentenceTransformer
    from app.services.jobsync_neural_scorer import (
        _build_model, _load_scorer_meta, _save_scorer_meta,
        MODELS_DIR, INPUT_DIM,
    )

    logger.info("Neural trainer starting", epochs=epochs, fine_tune=fine_tune)

    # Load embedder (use fine-tuned if available, else stock)
    try:
        from app.services.embedding_service import get_model
        embedder = get_model()
    except Exception:
        embedder = SentenceTransformer("all-mpnet-base-v2")

    # Load training data
    synthetic = _load_jsonl_data()
    all_records = synthetic + (feedback_records or [])

    if len(all_records) < MIN_SAMPLES:
        logger.warning(
            "Not enough training data",
            have=len(all_records),
            need=MIN_SAMPLES,
        )
        return {
            "status": "insufficient_data",
            "have": len(all_records),
            "need": MIN_SAMPLES,
        }

    logger.info("Building dataset (embedding all texts — may take a few minutes)...")
    dataset = ScoringDataset(all_records, embedder)

    if len(dataset) < MIN_SAMPLES:
        return {"status": "insufficient_data", "have": len(dataset), "need": MIN_SAMPLES}

    # Train/val split 85/15
    n_val = max(10, int(len(dataset) * 0.15))
    n_train = len(dataset) - n_val
    train_ds, val_ds = random_split(dataset, [n_train, n_val])

    train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True, num_workers=0)
    val_loader = DataLoader(val_ds, batch_size=BATCH_SIZE, shuffle=False, num_workers=0)

    # Model
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    logger.info("Using device", device=str(device))

    model = _build_model().to(device)

    # Load existing weights for fine-tuning
    if fine_tune:
        meta = _load_scorer_meta()
        v = meta.get("version", 0)
        if v > 0:
            existing = MODELS_DIR / f"jobsync-scorer-v{v}" / "model.pt"
            if existing.exists():
                state = torch.load(existing, map_location=device, weights_only=True)
                model.load_state_dict(state)
                logger.info("Loaded existing model for fine-tuning", version=v)

    optimizer = AdamW(model.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)
    scheduler = CosineAnnealingLR(optimizer, T_max=epochs, eta_min=1e-6)

    best_val_mse = float("inf")
    best_state = None
    patience_counter = 0
    history = []

    t_start = time.monotonic()

    for epoch in range(1, epochs + 1):
        # ── Train ──
        model.train()
        train_loss = 0.0
        for X_batch, y_batch in train_loader:
            X_batch = X_batch.to(device)
            y_batch = y_batch.to(device)

            optimizer.zero_grad()
            preds = model(X_batch)
            loss, mse, rank = combined_loss(preds, y_batch)
            loss.backward()

            nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()
            train_loss += mse.item()

        scheduler.step()
        avg_train_loss = train_loss / len(train_loader)

        # ── Validate ──
        model.eval()
        val_mse_total = 0.0
        val_mae_total = 0.0
        n_val_batches = 0

        with torch.no_grad():
            for X_batch, y_batch in val_loader:
                X_batch = X_batch.to(device)
                y_batch = y_batch.to(device)
                preds = model(X_batch)

                mse = nn.functional.mse_loss(preds, y_batch).item()
                mae = nn.functional.l1_loss(preds, y_batch).item()
                val_mse_total += mse
                val_mae_total += mae
                n_val_batches += 1

        avg_val_mse = val_mse_total / max(n_val_batches, 1)
        avg_val_mae = val_mae_total / max(n_val_batches, 1)

        history.append({
            "epoch": epoch,
            "train_mse": round(avg_train_loss, 4),
            "val_mse": round(avg_val_mse, 4),
            "val_mae": round(avg_val_mae, 4),
        })

        if epoch % 10 == 0 or epoch == 1:
            logger.info(
                "Training progress",
                epoch=epoch,
                total=epochs,
                train_mse=round(avg_train_loss, 3),
                val_mse=round(avg_val_mse, 3),
                val_mae=round(avg_val_mae, 3),
            )

        # Early stopping
        if avg_val_mse < best_val_mse - 0.1:
            best_val_mse = avg_val_mse
            best_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}
            patience_counter = 0
        else:
            patience_counter += 1
            if patience_counter >= PATIENCE:
                logger.info("Early stopping", epoch=epoch, best_val_mse=round(best_val_mse, 3))
                break

    elapsed = time.monotonic() - t_start

    if best_state is None:
        best_state = {k: v.cpu() for k, v in model.state_dict().items()}

    # Save model
    old_meta = _load_scorer_meta()
    new_version = old_meta.get("version", 0) + 1
    save_dir = MODELS_DIR / f"jobsync-scorer-v{new_version}"
    save_dir.mkdir(exist_ok=True)

    torch.save(best_state, save_dir / "model.pt")

    new_meta = {
        "version": new_version,
        "training_samples": len(dataset),
        "epochs_trained": epoch,
        "val_mse": round(best_val_mse, 4),
        "val_mae": round(avg_val_mae, 4),
        "last_trained_at": datetime.utcnow().isoformat(),
        "training_time_secs": round(elapsed, 1),
        "device": str(device),
        "fine_tuned": fine_tune,
    }
    _save_scorer_meta(new_meta)

    # Invalidate in-memory singleton so next request loads new model
    import app.services.jobsync_neural_scorer as ns
    ns._scorer_instance = None
    ns._scorer_loaded_at = 0.0

    logger.info(
        "Neural scorer training complete",
        version=new_version,
        val_mse=round(best_val_mse, 4),
        samples=len(dataset),
        elapsed_secs=round(elapsed, 1),
    )

    return {
        "status": "trained",
        "version": new_version,
        "samples": len(dataset),
        "epochs": epoch,
        "val_mse": round(best_val_mse, 4),
        "val_mae": round(avg_val_mae, 4),
        "elapsed_secs": round(elapsed, 1),
        "history": history[-10:],  # last 10 epochs
    }


async def train_async(epochs: int = DEFAULT_EPOCHS, fine_tune: bool = False) -> dict:
    """Async wrapper — loads feedback data then calls synchronous train()."""
    feedback = await _load_feedback_data()
    return await asyncio.to_thread(train, epochs, fine_tune, feedback)


# ─── CLI ───────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train JobSync Neural Scorer")
    parser.add_argument("--epochs", type=int, default=DEFAULT_EPOCHS)
    parser.add_argument("--fine-tune", action="store_true", help="Fine-tune existing model")
    args = parser.parse_args()

    import logging
    logging.basicConfig(level=logging.INFO)

    result = asyncio.run(train_async(epochs=args.epochs, fine_tune=args.fine_tune))
    print(json.dumps(result, indent=2))
